[workspace]
members = ["modelo-cli", "modelo-python"]
resolver = "2"

[package]
name = "modelo"
version = "0.9.0"
edition = "2024"
description = "A modular model validator"
license = "MIT"
repository = "https://github.com/heliocastro/modelo"
readme = "README.md"
keywords = ["ort", "sbom", "spdx", "validation"]
categories = ["parser-implementations"]
exclude = ["examples/*.py", ".github/*"]

[lib]
name = "modelo"
crate-type = ["rlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
thiserror = "1.0"
purl = { version = "0.1.6", features = ["serde", "package-type"] }
