default_install_hook_types = ["pre-commit", "commit-msg"]

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-yaml" },
  { id = "check-added-large-files" },
  { id = "check-symlinks" },
  {
    id = "mixed-line-ending",
    args = ["--fix=lf"]
  }
]

[[repos]]
repo = "https://github.com/codespell-project/codespell"
rev = "v2.4.3"
hooks = [
  { id = "codespell" }
]

[[repos]]

repo="https://github.com/rockmagma02/rust-pre-commit-hooks"
rev = "v0.2.0"
hooks = [
    { id = "rustfmt" },
    { id = "cargo-fmt" },
    { id = "clippy" }
]
