# SPDX-FileCopyrightText: 2026 Helio Chissini de Castro <dev@heliocastro.info>
# SPDX-License-Identifier: MIT
"""Type stubs for the Rust-implemented ORT model bindings."""

from typing import Any, Iterator

__all__ = [
    "LicenseClassifications",
    "Object",
    "OrtResult",
    "RepositoryConfiguration",
]

class Object:
    """A model instance: named fields plus the originating Rust type name."""

    def __init__(self, type_name: str, fields: dict[str, Any] | None = ...) -> None: ...
    @property
    def __type__(self) -> str: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[Any]: ...
    def items(self) -> list[tuple[str, Any]]: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __getattr__(self, name: str) -> Any: ...
    def __getitem__(self, name: str) -> Any: ...
    def __contains__(self, name: str) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def __dir__(self) -> list[str]: ...
    def __eq__(self, other: object) -> bool: ...

class _Model:
    @staticmethod
    def from_yaml_str(s: str) -> Any: ...
    @staticmethod
    def from_yaml_file(path: str) -> Any: ...
    def to_json(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    def keys(self) -> list[str]: ...
    def items(self) -> list[tuple[str, Any]]: ...
    def __getattr__(self, name: str) -> Any: ...
    def __getitem__(self, name: str) -> Any: ...
    def __contains__(self, name: str) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def __dir__(self) -> list[str]: ...

class LicenseClassifications(_Model):
    """A parsed and validated `license-classifications.yml`."""

    @staticmethod
    def from_yaml_str(s: str) -> LicenseClassifications: ...
    @staticmethod
    def from_yaml_file(path: str) -> LicenseClassifications: ...

class RepositoryConfiguration(_Model):
    """A parsed and validated `.ort.yml`."""

    @staticmethod
    def from_yaml_str(s: str) -> RepositoryConfiguration: ...
    @staticmethod
    def from_yaml_file(path: str) -> RepositoryConfiguration: ...

class OrtResult(_Model):
    """A parsed and validated ORT result file."""

    @staticmethod
    def from_yaml_str(s: str) -> OrtResult: ...
    @staticmethod
    def from_yaml_file(path: str) -> OrtResult: ...
