# SPDX-FileCopyrightText: 2026 Helio Chissini de Castro <dev@heliocastro.info>
# SPDX-License-Identifier: MIT
"""Type stubs for the Rust-implemented ORT model bindings."""

from typing import Any, Iterator

__all__ = [
    "AdvisorConfiguration",
    "AdvisorDetails",
    "AdvisorResult",
    "AdvisorRun",
    "AdvisorSummary",
    "AnalyzerConfiguration",
    "AnalyzerResult",
    "AnalyzerRun",
    "ArtifactProvenance",
    "BaseRun",
    "ClearlyDefinedStorageConfiguration",
    "CopyrightFinding",
    "Curations",
    "Defect",
    "DependencyGraph",
    "DependencyGraphEdge",
    "DependencyGraphNode",
    "DependencyReference",
    "Environment",
    "EvaluatorRun",
    "Excludes",
    "FileArchiverConfiguration",
    "FileBasedStorageConfiguration",
    "FileList",
    "FileListEntry",
    "FileListStorageConfiguration",
    "FileStorageConfiguration",
    "Hash",
    "HttpFileStorageConfiguration",
    "Identifier",
    "Includes",
    "Issue",
    "IssueResolution",
    "LicenseCategorization",
    "LicenseCategory",
    "LicenseChoices",
    "LicenseClassifications",
    "LicenseFinding",
    "LicenseFindingCuration",
    "LocalFileStorageConfiguration",
    "Object",
    "OrtResolutionIssue",
    "OrtResolutionRuleViolation",
    "OrtResolutions",
    "OrtResolutionVulnerability",
    "OrtResult",
    "Package",
    "PackageConfiguration",
    "PackageCuration",
    "PackageCurationData",
    "PackageLicenseChoice",
    "PackageManagerConfiguration",
    "PackageReference",
    "PathExclude",
    "PathInclude",
    "PostgresConnection",
    "PostgresStorageConfiguration",
    "ProcessedDeclaredLicense",
    "Project",
    "ProvenanceResolutionResult",
    "ProvenanceStorageConfiguration",
    "RemoteArtifact",
    "Repository",
    "RepositoryAnalyzerConfiguration",
    "RepositoryConfiguration",
    "RepositoryProvenance",
    "Resolutions",
    "RootDependencyIndex",
    "RuleViolation",
    "RuleViolationResolution",
    "S3FileStorageConfiguration",
    "ScanResult",
    "ScanStorageConfiguration",
    "ScanSummary",
    "ScannerConfiguration",
    "ScannerDetails",
    "ScannerRun",
    "Scope",
    "ScopeExclude",
    "Snippet",
    "SnippetChoice",
    "SnippetChoiceCriteria",
    "SnippetChoiceGiven",
    "SnippetChoices",
    "SnippetFinding",
    "SnippetProvenance",
    "SpdxLicenseChoice",
    "TextLocation",
    "VcsInfo",
    "VcsInfoCurationData",
    "VcsMatcher",
    "VcsType",
    "Vulnerability",
    "VulnerabilityReference",
    "VulnerabilityResolution",
]

class Object:
    """A model instance: named fields plus the originating Rust type name."""

    def __init__(self, type_name: str, fields: dict[str, Any] | None = ...) -> None: ...
    @property
    def __type__(self) -> str: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[Any]: ...
    def items(self) -> list[tuple[str, Any]]: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def to_yaml(self) -> str: ...
    def __getattr__(self, name: str) -> Any: ...
    def __getitem__(self, name: str) -> Any: ...
    def __contains__(self, name: str) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def __dir__(self) -> list[str]: ...
    def __eq__(self, other: object) -> bool: ...

class _NestedModel(Object):
    """A model reachable from the tree of `OrtResult`, `RepositoryConfiguration` or
    `LicenseClassifications`: same attribute-style access as `Object`, plus a name matching the
    originating Rust struct, e.g. `type(result.analyzer.result.projects[0].id).__name__ ==
    "Identifier"`.
    """

class AdvisorConfiguration(_NestedModel): ...
class AdvisorDetails(_NestedModel): ...
class AdvisorResult(_NestedModel): ...
class AdvisorRun(_NestedModel): ...
class AdvisorSummary(_NestedModel): ...
class AnalyzerConfiguration(_NestedModel): ...
class AnalyzerResult(_NestedModel): ...
class AnalyzerRun(_NestedModel): ...
class ArtifactProvenance(_NestedModel): ...
class BaseRun(_NestedModel): ...
class ClearlyDefinedStorageConfiguration(_NestedModel): ...
class CopyrightFinding(_NestedModel): ...
class Curations(_NestedModel): ...
class Defect(_NestedModel): ...
class DependencyGraph(_NestedModel): ...
class DependencyGraphEdge(_NestedModel): ...
class DependencyGraphNode(_NestedModel): ...
class DependencyReference(_NestedModel): ...
class Environment(_NestedModel): ...
class EvaluatorRun(_NestedModel): ...
class Excludes(_NestedModel): ...
class FileArchiverConfiguration(_NestedModel): ...
class FileBasedStorageConfiguration(_NestedModel): ...
class FileList(_NestedModel): ...
class FileListEntry(_NestedModel): ...
class FileListStorageConfiguration(_NestedModel): ...
class FileStorageConfiguration(_NestedModel): ...
class Hash(_NestedModel): ...
class HttpFileStorageConfiguration(_NestedModel): ...
class Identifier(_NestedModel): ...
class Includes(_NestedModel): ...
class Issue(_NestedModel): ...
class IssueResolution(_NestedModel): ...
class LicenseCategorization(_NestedModel): ...
class LicenseCategory(_NestedModel): ...
class LicenseChoices(_NestedModel): ...
class LicenseFinding(_NestedModel): ...
class LicenseFindingCuration(_NestedModel): ...
class LocalFileStorageConfiguration(_NestedModel): ...
class OrtResolutionIssue(_NestedModel): ...
class OrtResolutionRuleViolation(_NestedModel): ...
class OrtResolutions(_NestedModel): ...
class OrtResolutionVulnerability(_NestedModel): ...
class Package(_NestedModel): ...
class PackageConfiguration(_NestedModel): ...
class PackageCuration(_NestedModel): ...
class PackageCurationData(_NestedModel): ...
class PackageLicenseChoice(_NestedModel): ...
class PackageManagerConfiguration(_NestedModel): ...
class PackageReference(_NestedModel): ...
class PathExclude(_NestedModel): ...
class PathInclude(_NestedModel): ...
class PostgresConnection(_NestedModel): ...
class PostgresStorageConfiguration(_NestedModel): ...
class ProcessedDeclaredLicense(_NestedModel): ...
class Project(_NestedModel): ...
class ProvenanceResolutionResult(_NestedModel): ...
class ProvenanceStorageConfiguration(_NestedModel): ...
class RemoteArtifact(_NestedModel): ...
class Repository(_NestedModel): ...
class RepositoryAnalyzerConfiguration(_NestedModel): ...
class RepositoryProvenance(_NestedModel): ...
class Resolutions(_NestedModel): ...
class RootDependencyIndex(_NestedModel): ...
class RuleViolation(_NestedModel): ...
class RuleViolationResolution(_NestedModel): ...
class S3FileStorageConfiguration(_NestedModel): ...
class ScanResult(_NestedModel): ...
class ScanStorageConfiguration(_NestedModel): ...
class ScanSummary(_NestedModel): ...
class ScannerConfiguration(_NestedModel): ...
class ScannerDetails(_NestedModel): ...
class ScannerRun(_NestedModel): ...
class Scope(_NestedModel): ...
class ScopeExclude(_NestedModel): ...
class Snippet(_NestedModel): ...
class SnippetChoice(_NestedModel): ...
class SnippetChoiceCriteria(_NestedModel): ...
class SnippetChoiceGiven(_NestedModel): ...
class SnippetChoices(_NestedModel): ...
class SnippetFinding(_NestedModel): ...
class SnippetProvenance(_NestedModel): ...
class SpdxLicenseChoice(_NestedModel): ...
class TextLocation(_NestedModel): ...
class VcsInfo(_NestedModel): ...
class VcsInfoCurationData(_NestedModel): ...
class VcsMatcher(_NestedModel): ...
class VcsType(_NestedModel): ...
class Vulnerability(_NestedModel): ...
class VulnerabilityReference(_NestedModel): ...
class VulnerabilityResolution(_NestedModel): ...

class _Model:
    @staticmethod
    def from_yaml_str(s: str) -> Any: ...
    @staticmethod
    def from_yaml_file(path: str) -> Any: ...
    def to_json(self) -> str: ...
    def to_yaml(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    def keys(self) -> list[str]: ...
    def items(self) -> list[tuple[str, Any]]: ...
    def __getattr__(self, name: str) -> Any: ...
    def __getitem__(self, name: str) -> Any: ...
    def __contains__(self, name: str) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def __dir__(self) -> list[str]: ...

class LicenseClassifications(_Model):
    """A parsed and validated `license-classifications.yml`."""

    @staticmethod
    def from_yaml_str(s: str) -> LicenseClassifications: ...
    @staticmethod
    def from_yaml_file(path: str) -> LicenseClassifications: ...

class RepositoryConfiguration(_Model):
    """A parsed and validated `.ort.yml`."""

    @staticmethod
    def from_yaml_str(s: str) -> RepositoryConfiguration: ...
    @staticmethod
    def from_yaml_file(path: str) -> RepositoryConfiguration: ...

class OrtResult(_Model):
    """A parsed and validated ORT result file."""

    @staticmethod
    def from_yaml_str(s: str) -> OrtResult: ...
    @staticmethod
    def from_yaml_file(path: str) -> OrtResult: ...
